language: python
dist: precise
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- py.test
- pyinstaller --onefile --hidden-import tkinter.filedialog  ./src/obj2png.py
deploy:
  provider: releases
  api_key:
    secure: TsssMKC1jrJ5cFzAvGmXmFSr2Z6HlneZjPY/ZNJyb/A4yVPk8hrE7KONV9cVD2x0ex2S/Fb6MMcC73db2P7Q/6PqA3nrFL8vNpPfvHqW8aE1f+xuin0cXubXLZ/Wrg5FjAT+W1QtGwxBkEOme9KBTrElHbVK2rYxVgIqNhfAXDP1+z4gTycpDHiFYy9Ff8jhbZuA0iyjoGUh8XMeIUDfVMJ3paALOcMTUkw+AhQgzf9UL7foIEPwnHwP6KgQ/nWeBy8OCXYP1ETJsdfiheXzTNUfETdKHuto6nKzk+BApuwJY+rpFZuPRkx6bLBa2dXxKmGDD59zVGjVGzp8IGkP6j23qFIAno9c9lvw6FiMRQfYKfCwdGCX814eirkxdlRAPqk5rRmxR3iuyGKap4MWOKNPXziuV+o6RUj3qAOY/vvnUobq9lal6DcPUw2iRIlAi+ze4Ph0eN8DDA+JpdpKRMxXAVrACLzWbNl2BffKuiZPHqTcTiKT6LUdvJMdkUhq8e9UTvPmO0+HeDjoKbSw6HC3F7kuC0gsGsH24P+coeqjHTk/yXpnqIs2R+zpF23fUW0tDd6emYnPZFVQHxxsIWYYd9oijH7jtMmN+g/j9bcc+oiFsGhup5I3Iujlpy13ZAqb1s9GpZdMdA85o6bD/GxjFGfd4qXbk6I2iLZs6AA=
  file: dist/obj2png
  skip-cleanup: true
  keep-history: true  
  on:
    repo: pclausen/obj2png	
    python: '3.5'


